/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from '@prisma/client/runtime/client'
import * as path from 'node:path'
import * as process from 'node:process'
import { fileURLToPath } from 'node:url'

import * as $Enums from './enums'
import * as $Class from './internal/class'
import * as Prisma from './internal/prismaNamespace'

globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

export * as $Enums from './enums'
export * from './enums'
/**
 * ## Prisma Client
 *
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more AwesomeCatelogs
 * const awesomeCatelogs = await prisma.awesomeCatelog.findMany()
 * ```
 *
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<
  LogOpts extends Prisma.LogLevel = never,
  OmitOpts extends Prisma.PrismaClientOptions['omit'] = Prisma.PrismaClientOptions['omit'],
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model AwesomeCatelog
 * Awesome 类别，存在父子级别
 */
export type AwesomeCatelog = Prisma.AwesomeCatelogModel
/**
 * Model AwesomeTag
 * Awesome 的标签
 */
export type AwesomeTag = Prisma.AwesomeTagModel
/**
 * Model AwesomeItem
 * Awesome 项
 */
export type AwesomeItem = Prisma.AwesomeItemModel
/**
 * Model Short
 * 短网址记录
 */
export type Short = Prisma.ShortModel
/**
 * Model User
 * 用户（由 btter-auth 创建）
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 会话（由 btter-auth 创建）
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 账户（由 btter-auth 创建）
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * 验证（由 btter-auth 创建）
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Apikey
 * 账号 API（由 btter-auth 创建）
 */
export type Apikey = Prisma.ApikeyModel
