/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const ShortRedirectType = {
  PERMANENTLY: 'PERMANENTLY',
  TEMPORARY: 'TEMPORARY',
  JAVASCRIPT: 'JAVASCRIPT',
} as const

export type ShortRedirectType = (typeof ShortRedirectType)[keyof typeof ShortRedirectType]
