/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Short` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'

import type * as $Enums from '../enums'
import type * as Prisma from '../internal/prismaNamespace'

/**
 * Model Short
 * 短网址记录
 */
export type ShortModel = runtime.Types.Result.DefaultSelection<Prisma.$ShortPayload>

export type AggregateShort = {
  _count: ShortCountAggregateOutputType | null
  _min: ShortMinAggregateOutputType | null
  _max: ShortMaxAggregateOutputType | null
}

export type ShortMinAggregateOutputType = {
  id: string | null
  url: string | null
  key: string | null
  tag: string | null
  redirectType: $Enums.ShortRedirectType | null
  expiredAt: Date | null
  public: boolean | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ShortMaxAggregateOutputType = {
  id: string | null
  url: string | null
  key: string | null
  tag: string | null
  redirectType: $Enums.ShortRedirectType | null
  expiredAt: Date | null
  public: boolean | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ShortCountAggregateOutputType = {
  id: number
  url: number
  key: number
  tag: number
  redirectType: number
  expiredAt: number
  public: number
  userId: number
  createdAt: number
  updatedAt: number
  _all: number
}

export type ShortMinAggregateInputType = {
  id?: true
  url?: true
  key?: true
  tag?: true
  redirectType?: true
  expiredAt?: true
  public?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type ShortMaxAggregateInputType = {
  id?: true
  url?: true
  key?: true
  tag?: true
  redirectType?: true
  expiredAt?: true
  public?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type ShortCountAggregateInputType = {
  id?: true
  url?: true
  key?: true
  tag?: true
  redirectType?: true
  expiredAt?: true
  public?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ShortAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Short to aggregate.
   */
  where?: Prisma.ShortWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Shorts to fetch.
   */
  orderBy?: Prisma.ShortOrderByWithRelationInput | Prisma.ShortOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ShortWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Shorts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Shorts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned Shorts
   **/
  _count?: true | ShortCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ShortMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ShortMaxAggregateInputType
}

export type GetShortAggregateType<T extends ShortAggregateArgs> = {
  [P in keyof T & keyof AggregateShort]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateShort[P]>
    : Prisma.GetScalarType<T[P], AggregateShort[P]>
}

export type ShortGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ShortWhereInput
  orderBy?: Prisma.ShortOrderByWithAggregationInput | Prisma.ShortOrderByWithAggregationInput[]
  by: Prisma.ShortScalarFieldEnum[] | Prisma.ShortScalarFieldEnum
  having?: Prisma.ShortScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ShortCountAggregateInputType | true
  _min?: ShortMinAggregateInputType
  _max?: ShortMaxAggregateInputType
}

export type ShortGroupByOutputType = {
  id: string
  url: string
  key: string
  tag: string | null
  redirectType: $Enums.ShortRedirectType
  expiredAt: Date | null
  public: boolean
  userId: string | null
  createdAt: Date
  updatedAt: Date
  _count: ShortCountAggregateOutputType | null
  _min: ShortMinAggregateOutputType | null
  _max: ShortMaxAggregateOutputType | null
}

type GetShortGroupByPayload<T extends ShortGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ShortGroupByOutputType, T['by']> & {
      [P in keyof T & keyof ShortGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], ShortGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], ShortGroupByOutputType[P]>
    }
  >
>

export type ShortWhereInput = {
  AND?: Prisma.ShortWhereInput | Prisma.ShortWhereInput[]
  OR?: Prisma.ShortWhereInput[]
  NOT?: Prisma.ShortWhereInput | Prisma.ShortWhereInput[]
  id?: Prisma.StringFilter<'Short'> | string
  url?: Prisma.StringFilter<'Short'> | string
  key?: Prisma.StringFilter<'Short'> | string
  tag?: Prisma.StringNullableFilter<'Short'> | string | null
  redirectType?: Prisma.EnumShortRedirectTypeFilter<'Short'> | $Enums.ShortRedirectType
  expiredAt?: Prisma.DateTimeNullableFilter<'Short'> | Date | string | null
  public?: Prisma.BoolFilter<'Short'> | boolean
  userId?: Prisma.StringNullableFilter<'Short'> | string | null
  createdAt?: Prisma.DateTimeFilter<'Short'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'Short'> | Date | string
  author?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type ShortOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  key?: Prisma.SortOrder
  tag?: Prisma.SortOrderInput | Prisma.SortOrder
  redirectType?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrderInput | Prisma.SortOrder
  public?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  author?: Prisma.UserOrderByWithRelationInput
}

export type ShortWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?: Prisma.ShortWhereInput | Prisma.ShortWhereInput[]
    OR?: Prisma.ShortWhereInput[]
    NOT?: Prisma.ShortWhereInput | Prisma.ShortWhereInput[]
    url?: Prisma.StringFilter<'Short'> | string
    key?: Prisma.StringFilter<'Short'> | string
    tag?: Prisma.StringNullableFilter<'Short'> | string | null
    redirectType?: Prisma.EnumShortRedirectTypeFilter<'Short'> | $Enums.ShortRedirectType
    expiredAt?: Prisma.DateTimeNullableFilter<'Short'> | Date | string | null
    public?: Prisma.BoolFilter<'Short'> | boolean
    userId?: Prisma.StringNullableFilter<'Short'> | string | null
    createdAt?: Prisma.DateTimeFilter<'Short'> | Date | string
    updatedAt?: Prisma.DateTimeFilter<'Short'> | Date | string
    author?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  },
  'id'
>

export type ShortOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  key?: Prisma.SortOrder
  tag?: Prisma.SortOrderInput | Prisma.SortOrder
  redirectType?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrderInput | Prisma.SortOrder
  public?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ShortCountOrderByAggregateInput
  _max?: Prisma.ShortMaxOrderByAggregateInput
  _min?: Prisma.ShortMinOrderByAggregateInput
}

export type ShortScalarWhereWithAggregatesInput = {
  AND?: Prisma.ShortScalarWhereWithAggregatesInput | Prisma.ShortScalarWhereWithAggregatesInput[]
  OR?: Prisma.ShortScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ShortScalarWhereWithAggregatesInput | Prisma.ShortScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<'Short'> | string
  url?: Prisma.StringWithAggregatesFilter<'Short'> | string
  key?: Prisma.StringWithAggregatesFilter<'Short'> | string
  tag?: Prisma.StringNullableWithAggregatesFilter<'Short'> | string | null
  redirectType?:
    | Prisma.EnumShortRedirectTypeWithAggregatesFilter<'Short'>
    | $Enums.ShortRedirectType
  expiredAt?: Prisma.DateTimeNullableWithAggregatesFilter<'Short'> | Date | string | null
  public?: Prisma.BoolWithAggregatesFilter<'Short'> | boolean
  userId?: Prisma.StringNullableWithAggregatesFilter<'Short'> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'Short'> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<'Short'> | Date | string
}

export type ShortCreateInput = {
  id?: string
  url: string
  key: string
  tag?: string | null
  redirectType?: $Enums.ShortRedirectType
  expiredAt?: Date | string | null
  public?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  author?: Prisma.UserCreateNestedOneWithoutShortInput
}

export type ShortUncheckedCreateInput = {
  id?: string
  url: string
  key: string
  tag?: string | null
  redirectType?: $Enums.ShortRedirectType
  expiredAt?: Date | string | null
  public?: boolean
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShortUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectType?: Prisma.EnumShortRedirectTypeFieldUpdateOperationsInput | $Enums.ShortRedirectType
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  author?: Prisma.UserUpdateOneWithoutShortNestedInput
}

export type ShortUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectType?: Prisma.EnumShortRedirectTypeFieldUpdateOperationsInput | $Enums.ShortRedirectType
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShortCreateManyInput = {
  id?: string
  url: string
  key: string
  tag?: string | null
  redirectType?: $Enums.ShortRedirectType
  expiredAt?: Date | string | null
  public?: boolean
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShortUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectType?: Prisma.EnumShortRedirectTypeFieldUpdateOperationsInput | $Enums.ShortRedirectType
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShortUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectType?: Prisma.EnumShortRedirectTypeFieldUpdateOperationsInput | $Enums.ShortRedirectType
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShortCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  key?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  redirectType?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  public?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ShortMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  key?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  redirectType?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  public?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ShortMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  key?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  redirectType?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  public?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ShortListRelationFilter = {
  every?: Prisma.ShortWhereInput
  some?: Prisma.ShortWhereInput
  none?: Prisma.ShortWhereInput
}

export type ShortOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EnumShortRedirectTypeFieldUpdateOperationsInput = {
  set?: $Enums.ShortRedirectType
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type ShortCreateNestedManyWithoutAuthorInput = {
  create?:
    | Prisma.XOR<
        Prisma.ShortCreateWithoutAuthorInput,
        Prisma.ShortUncheckedCreateWithoutAuthorInput
      >
    | Prisma.ShortCreateWithoutAuthorInput[]
    | Prisma.ShortUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?:
    | Prisma.ShortCreateOrConnectWithoutAuthorInput
    | Prisma.ShortCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.ShortCreateManyAuthorInputEnvelope
  connect?: Prisma.ShortWhereUniqueInput | Prisma.ShortWhereUniqueInput[]
}

export type ShortUncheckedCreateNestedManyWithoutAuthorInput = {
  create?:
    | Prisma.XOR<
        Prisma.ShortCreateWithoutAuthorInput,
        Prisma.ShortUncheckedCreateWithoutAuthorInput
      >
    | Prisma.ShortCreateWithoutAuthorInput[]
    | Prisma.ShortUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?:
    | Prisma.ShortCreateOrConnectWithoutAuthorInput
    | Prisma.ShortCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.ShortCreateManyAuthorInputEnvelope
  connect?: Prisma.ShortWhereUniqueInput | Prisma.ShortWhereUniqueInput[]
}

export type ShortUpdateManyWithoutAuthorNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ShortCreateWithoutAuthorInput,
        Prisma.ShortUncheckedCreateWithoutAuthorInput
      >
    | Prisma.ShortCreateWithoutAuthorInput[]
    | Prisma.ShortUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?:
    | Prisma.ShortCreateOrConnectWithoutAuthorInput
    | Prisma.ShortCreateOrConnectWithoutAuthorInput[]
  upsert?:
    | Prisma.ShortUpsertWithWhereUniqueWithoutAuthorInput
    | Prisma.ShortUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.ShortCreateManyAuthorInputEnvelope
  set?: Prisma.ShortWhereUniqueInput | Prisma.ShortWhereUniqueInput[]
  disconnect?: Prisma.ShortWhereUniqueInput | Prisma.ShortWhereUniqueInput[]
  delete?: Prisma.ShortWhereUniqueInput | Prisma.ShortWhereUniqueInput[]
  connect?: Prisma.ShortWhereUniqueInput | Prisma.ShortWhereUniqueInput[]
  update?:
    | Prisma.ShortUpdateWithWhereUniqueWithoutAuthorInput
    | Prisma.ShortUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?:
    | Prisma.ShortUpdateManyWithWhereWithoutAuthorInput
    | Prisma.ShortUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.ShortScalarWhereInput | Prisma.ShortScalarWhereInput[]
}

export type ShortUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ShortCreateWithoutAuthorInput,
        Prisma.ShortUncheckedCreateWithoutAuthorInput
      >
    | Prisma.ShortCreateWithoutAuthorInput[]
    | Prisma.ShortUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?:
    | Prisma.ShortCreateOrConnectWithoutAuthorInput
    | Prisma.ShortCreateOrConnectWithoutAuthorInput[]
  upsert?:
    | Prisma.ShortUpsertWithWhereUniqueWithoutAuthorInput
    | Prisma.ShortUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.ShortCreateManyAuthorInputEnvelope
  set?: Prisma.ShortWhereUniqueInput | Prisma.ShortWhereUniqueInput[]
  disconnect?: Prisma.ShortWhereUniqueInput | Prisma.ShortWhereUniqueInput[]
  delete?: Prisma.ShortWhereUniqueInput | Prisma.ShortWhereUniqueInput[]
  connect?: Prisma.ShortWhereUniqueInput | Prisma.ShortWhereUniqueInput[]
  update?:
    | Prisma.ShortUpdateWithWhereUniqueWithoutAuthorInput
    | Prisma.ShortUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?:
    | Prisma.ShortUpdateManyWithWhereWithoutAuthorInput
    | Prisma.ShortUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.ShortScalarWhereInput | Prisma.ShortScalarWhereInput[]
}

export type ShortCreateWithoutAuthorInput = {
  id?: string
  url: string
  key: string
  tag?: string | null
  redirectType?: $Enums.ShortRedirectType
  expiredAt?: Date | string | null
  public?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShortUncheckedCreateWithoutAuthorInput = {
  id?: string
  url: string
  key: string
  tag?: string | null
  redirectType?: $Enums.ShortRedirectType
  expiredAt?: Date | string | null
  public?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShortCreateOrConnectWithoutAuthorInput = {
  where: Prisma.ShortWhereUniqueInput
  create: Prisma.XOR<
    Prisma.ShortCreateWithoutAuthorInput,
    Prisma.ShortUncheckedCreateWithoutAuthorInput
  >
}

export type ShortCreateManyAuthorInputEnvelope = {
  data: Prisma.ShortCreateManyAuthorInput | Prisma.ShortCreateManyAuthorInput[]
  skipDuplicates?: boolean
}

export type ShortUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.ShortWhereUniqueInput
  update: Prisma.XOR<
    Prisma.ShortUpdateWithoutAuthorInput,
    Prisma.ShortUncheckedUpdateWithoutAuthorInput
  >
  create: Prisma.XOR<
    Prisma.ShortCreateWithoutAuthorInput,
    Prisma.ShortUncheckedCreateWithoutAuthorInput
  >
}

export type ShortUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.ShortWhereUniqueInput
  data: Prisma.XOR<
    Prisma.ShortUpdateWithoutAuthorInput,
    Prisma.ShortUncheckedUpdateWithoutAuthorInput
  >
}

export type ShortUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.ShortScalarWhereInput
  data: Prisma.XOR<
    Prisma.ShortUpdateManyMutationInput,
    Prisma.ShortUncheckedUpdateManyWithoutAuthorInput
  >
}

export type ShortScalarWhereInput = {
  AND?: Prisma.ShortScalarWhereInput | Prisma.ShortScalarWhereInput[]
  OR?: Prisma.ShortScalarWhereInput[]
  NOT?: Prisma.ShortScalarWhereInput | Prisma.ShortScalarWhereInput[]
  id?: Prisma.StringFilter<'Short'> | string
  url?: Prisma.StringFilter<'Short'> | string
  key?: Prisma.StringFilter<'Short'> | string
  tag?: Prisma.StringNullableFilter<'Short'> | string | null
  redirectType?: Prisma.EnumShortRedirectTypeFilter<'Short'> | $Enums.ShortRedirectType
  expiredAt?: Prisma.DateTimeNullableFilter<'Short'> | Date | string | null
  public?: Prisma.BoolFilter<'Short'> | boolean
  userId?: Prisma.StringNullableFilter<'Short'> | string | null
  createdAt?: Prisma.DateTimeFilter<'Short'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'Short'> | Date | string
}

export type ShortCreateManyAuthorInput = {
  id?: string
  url: string
  key: string
  tag?: string | null
  redirectType?: $Enums.ShortRedirectType
  expiredAt?: Date | string | null
  public?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShortUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectType?: Prisma.EnumShortRedirectTypeFieldUpdateOperationsInput | $Enums.ShortRedirectType
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShortUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectType?: Prisma.EnumShortRedirectTypeFieldUpdateOperationsInput | $Enums.ShortRedirectType
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShortUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectType?: Prisma.EnumShortRedirectTypeFieldUpdateOperationsInput | $Enums.ShortRedirectType
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShortSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    url?: boolean
    key?: boolean
    tag?: boolean
    redirectType?: boolean
    expiredAt?: boolean
    public?: boolean
    userId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    author?: boolean | Prisma.Short$authorArgs<ExtArgs>
  },
  ExtArgs['result']['short']
>

export type ShortSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    url?: boolean
    key?: boolean
    tag?: boolean
    redirectType?: boolean
    expiredAt?: boolean
    public?: boolean
    userId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    author?: boolean | Prisma.Short$authorArgs<ExtArgs>
  },
  ExtArgs['result']['short']
>

export type ShortSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    url?: boolean
    key?: boolean
    tag?: boolean
    redirectType?: boolean
    expiredAt?: boolean
    public?: boolean
    userId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    author?: boolean | Prisma.Short$authorArgs<ExtArgs>
  },
  ExtArgs['result']['short']
>

export type ShortSelectScalar = {
  id?: boolean
  url?: boolean
  key?: boolean
  tag?: boolean
  redirectType?: boolean
  expiredAt?: boolean
  public?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ShortOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'url'
  | 'key'
  | 'tag'
  | 'redirectType'
  | 'expiredAt'
  | 'public'
  | 'userId'
  | 'createdAt'
  | 'updatedAt',
  ExtArgs['result']['short']
>
export type ShortInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  author?: boolean | Prisma.Short$authorArgs<ExtArgs>
}
export type ShortIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  author?: boolean | Prisma.Short$authorArgs<ExtArgs>
}
export type ShortIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  author?: boolean | Prisma.Short$authorArgs<ExtArgs>
}

export type $ShortPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'Short'
  objects: {
    author: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      url: string
      key: string
      tag: string | null
      redirectType: $Enums.ShortRedirectType
      expiredAt: Date | null
      public: boolean
      userId: string | null
      createdAt: Date
      updatedAt: Date
    },
    ExtArgs['result']['short']
  >
  composites: {}
}

export type ShortGetPayload<S extends boolean | null | undefined | ShortDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$ShortPayload, S>

export type ShortCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<ShortFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: ShortCountAggregateInputType | true
}

export interface ShortDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Short']; meta: { name: 'Short' } }
  /**
   * Find zero or one Short that matches the filter.
   * @param {ShortFindUniqueArgs} args - Arguments to find a Short
   * @example
   * // Get one Short
   * const short = await prisma.short.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ShortFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ShortFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__ShortClient<
    runtime.Types.Result.GetResult<
      Prisma.$ShortPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one Short that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ShortFindUniqueOrThrowArgs} args - Arguments to find a Short
   * @example
   * // Get one Short
   * const short = await prisma.short.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ShortFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, ShortFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__ShortClient<
    runtime.Types.Result.GetResult<
      Prisma.$ShortPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Short that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShortFindFirstArgs} args - Arguments to find a Short
   * @example
   * // Get one Short
   * const short = await prisma.short.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ShortFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ShortFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__ShortClient<
    runtime.Types.Result.GetResult<
      Prisma.$ShortPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Short that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShortFindFirstOrThrowArgs} args - Arguments to find a Short
   * @example
   * // Get one Short
   * const short = await prisma.short.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ShortFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, ShortFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__ShortClient<
    runtime.Types.Result.GetResult<
      Prisma.$ShortPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more Shorts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShortFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Shorts
   * const shorts = await prisma.short.findMany()
   *
   * // Get first 10 Shorts
   * const shorts = await prisma.short.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const shortWithIdOnly = await prisma.short.findMany({ select: { id: true } })
   *
   */
  findMany<T extends ShortFindManyArgs>(
    args?: Prisma.SelectSubset<T, ShortFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$ShortPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions>
  >

  /**
   * Create a Short.
   * @param {ShortCreateArgs} args - Arguments to create a Short.
   * @example
   * // Create one Short
   * const Short = await prisma.short.create({
   *   data: {
   *     // ... data to create a Short
   *   }
   * })
   *
   */
  create<T extends ShortCreateArgs>(
    args: Prisma.SelectSubset<T, ShortCreateArgs<ExtArgs>>
  ): Prisma.Prisma__ShortClient<
    runtime.Types.Result.GetResult<Prisma.$ShortPayload<ExtArgs>, T, 'create', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many Shorts.
   * @param {ShortCreateManyArgs} args - Arguments to create many Shorts.
   * @example
   * // Create many Shorts
   * const short = await prisma.short.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ShortCreateManyArgs>(
    args?: Prisma.SelectSubset<T, ShortCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Shorts and returns the data saved in the database.
   * @param {ShortCreateManyAndReturnArgs} args - Arguments to create many Shorts.
   * @example
   * // Create many Shorts
   * const short = await prisma.short.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many Shorts and only return the `id`
   * const shortWithIdOnly = await prisma.short.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends ShortCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, ShortCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ShortPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Delete a Short.
   * @param {ShortDeleteArgs} args - Arguments to delete one Short.
   * @example
   * // Delete one Short
   * const Short = await prisma.short.delete({
   *   where: {
   *     // ... filter to delete one Short
   *   }
   * })
   *
   */
  delete<T extends ShortDeleteArgs>(
    args: Prisma.SelectSubset<T, ShortDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__ShortClient<
    runtime.Types.Result.GetResult<Prisma.$ShortPayload<ExtArgs>, T, 'delete', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one Short.
   * @param {ShortUpdateArgs} args - Arguments to update one Short.
   * @example
   * // Update one Short
   * const short = await prisma.short.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ShortUpdateArgs>(
    args: Prisma.SelectSubset<T, ShortUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__ShortClient<
    runtime.Types.Result.GetResult<Prisma.$ShortPayload<ExtArgs>, T, 'update', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more Shorts.
   * @param {ShortDeleteManyArgs} args - Arguments to filter Shorts to delete.
   * @example
   * // Delete a few Shorts
   * const { count } = await prisma.short.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ShortDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, ShortDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Shorts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShortUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Shorts
   * const short = await prisma.short.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ShortUpdateManyArgs>(
    args: Prisma.SelectSubset<T, ShortUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Shorts and returns the data updated in the database.
   * @param {ShortUpdateManyAndReturnArgs} args - Arguments to update many Shorts.
   * @example
   * // Update many Shorts
   * const short = await prisma.short.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more Shorts and only return the `id`
   * const shortWithIdOnly = await prisma.short.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends ShortUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, ShortUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ShortPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one Short.
   * @param {ShortUpsertArgs} args - Arguments to update or create a Short.
   * @example
   * // Update or create a Short
   * const short = await prisma.short.upsert({
   *   create: {
   *     // ... data to create a Short
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Short we want to update
   *   }
   * })
   */
  upsert<T extends ShortUpsertArgs>(
    args: Prisma.SelectSubset<T, ShortUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__ShortClient<
    runtime.Types.Result.GetResult<Prisma.$ShortPayload<ExtArgs>, T, 'upsert', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of Shorts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShortCountArgs} args - Arguments to filter Shorts to count.
   * @example
   * // Count the number of Shorts
   * const count = await prisma.short.count({
   *   where: {
   *     // ... the filter for the Shorts we want to count
   *   }
   * })
   **/
  count<T extends ShortCountArgs>(
    args?: Prisma.Subset<T, ShortCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ShortCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Short.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShortAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ShortAggregateArgs>(
    args: Prisma.Subset<T, ShortAggregateArgs>
  ): Prisma.PrismaPromise<GetShortAggregateType<T>>

  /**
   * Group by Short.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShortGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ShortGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ShortGroupByArgs['orderBy'] }
      : { orderBy?: ShortGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, ShortGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors ? GetShortGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the Short model
   */
  readonly fields: ShortFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for Short.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ShortClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  author<T extends Prisma.Short$authorArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.Short$authorArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the Short model
 */
export interface ShortFieldRefs {
  readonly id: Prisma.FieldRef<'Short', 'String'>
  readonly url: Prisma.FieldRef<'Short', 'String'>
  readonly key: Prisma.FieldRef<'Short', 'String'>
  readonly tag: Prisma.FieldRef<'Short', 'String'>
  readonly redirectType: Prisma.FieldRef<'Short', 'ShortRedirectType'>
  readonly expiredAt: Prisma.FieldRef<'Short', 'DateTime'>
  readonly public: Prisma.FieldRef<'Short', 'Boolean'>
  readonly userId: Prisma.FieldRef<'Short', 'String'>
  readonly createdAt: Prisma.FieldRef<'Short', 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<'Short', 'DateTime'>
}

// Custom InputTypes
/**
 * Short findUnique
 */
export type ShortFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Short
   */
  select?: Prisma.ShortSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Short
   */
  omit?: Prisma.ShortOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortInclude<ExtArgs> | null
  /**
   * Filter, which Short to fetch.
   */
  where: Prisma.ShortWhereUniqueInput
}

/**
 * Short findUniqueOrThrow
 */
export type ShortFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Short
   */
  select?: Prisma.ShortSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Short
   */
  omit?: Prisma.ShortOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortInclude<ExtArgs> | null
  /**
   * Filter, which Short to fetch.
   */
  where: Prisma.ShortWhereUniqueInput
}

/**
 * Short findFirst
 */
export type ShortFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Short
   */
  select?: Prisma.ShortSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Short
   */
  omit?: Prisma.ShortOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortInclude<ExtArgs> | null
  /**
   * Filter, which Short to fetch.
   */
  where?: Prisma.ShortWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Shorts to fetch.
   */
  orderBy?: Prisma.ShortOrderByWithRelationInput | Prisma.ShortOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Shorts.
   */
  cursor?: Prisma.ShortWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Shorts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Shorts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Shorts.
   */
  distinct?: Prisma.ShortScalarFieldEnum | Prisma.ShortScalarFieldEnum[]
}

/**
 * Short findFirstOrThrow
 */
export type ShortFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Short
   */
  select?: Prisma.ShortSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Short
   */
  omit?: Prisma.ShortOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortInclude<ExtArgs> | null
  /**
   * Filter, which Short to fetch.
   */
  where?: Prisma.ShortWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Shorts to fetch.
   */
  orderBy?: Prisma.ShortOrderByWithRelationInput | Prisma.ShortOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Shorts.
   */
  cursor?: Prisma.ShortWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Shorts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Shorts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Shorts.
   */
  distinct?: Prisma.ShortScalarFieldEnum | Prisma.ShortScalarFieldEnum[]
}

/**
 * Short findMany
 */
export type ShortFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Short
   */
  select?: Prisma.ShortSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Short
   */
  omit?: Prisma.ShortOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortInclude<ExtArgs> | null
  /**
   * Filter, which Shorts to fetch.
   */
  where?: Prisma.ShortWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Shorts to fetch.
   */
  orderBy?: Prisma.ShortOrderByWithRelationInput | Prisma.ShortOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing Shorts.
   */
  cursor?: Prisma.ShortWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Shorts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Shorts.
   */
  skip?: number
  distinct?: Prisma.ShortScalarFieldEnum | Prisma.ShortScalarFieldEnum[]
}

/**
 * Short create
 */
export type ShortCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Short
   */
  select?: Prisma.ShortSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Short
   */
  omit?: Prisma.ShortOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortInclude<ExtArgs> | null
  /**
   * The data needed to create a Short.
   */
  data: Prisma.XOR<Prisma.ShortCreateInput, Prisma.ShortUncheckedCreateInput>
}

/**
 * Short createMany
 */
export type ShortCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many Shorts.
   */
  data: Prisma.ShortCreateManyInput | Prisma.ShortCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Short createManyAndReturn
 */
export type ShortCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Short
   */
  select?: Prisma.ShortSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Short
   */
  omit?: Prisma.ShortOmit<ExtArgs> | null
  /**
   * The data used to create many Shorts.
   */
  data: Prisma.ShortCreateManyInput | Prisma.ShortCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Short update
 */
export type ShortUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Short
   */
  select?: Prisma.ShortSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Short
   */
  omit?: Prisma.ShortOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortInclude<ExtArgs> | null
  /**
   * The data needed to update a Short.
   */
  data: Prisma.XOR<Prisma.ShortUpdateInput, Prisma.ShortUncheckedUpdateInput>
  /**
   * Choose, which Short to update.
   */
  where: Prisma.ShortWhereUniqueInput
}

/**
 * Short updateMany
 */
export type ShortUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update Shorts.
   */
  data: Prisma.XOR<Prisma.ShortUpdateManyMutationInput, Prisma.ShortUncheckedUpdateManyInput>
  /**
   * Filter which Shorts to update
   */
  where?: Prisma.ShortWhereInput
  /**
   * Limit how many Shorts to update.
   */
  limit?: number
}

/**
 * Short updateManyAndReturn
 */
export type ShortUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Short
   */
  select?: Prisma.ShortSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Short
   */
  omit?: Prisma.ShortOmit<ExtArgs> | null
  /**
   * The data used to update Shorts.
   */
  data: Prisma.XOR<Prisma.ShortUpdateManyMutationInput, Prisma.ShortUncheckedUpdateManyInput>
  /**
   * Filter which Shorts to update
   */
  where?: Prisma.ShortWhereInput
  /**
   * Limit how many Shorts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Short upsert
 */
export type ShortUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Short
   */
  select?: Prisma.ShortSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Short
   */
  omit?: Prisma.ShortOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortInclude<ExtArgs> | null
  /**
   * The filter to search for the Short to update in case it exists.
   */
  where: Prisma.ShortWhereUniqueInput
  /**
   * In case the Short found by the `where` argument doesn't exist, create a new Short with this data.
   */
  create: Prisma.XOR<Prisma.ShortCreateInput, Prisma.ShortUncheckedCreateInput>
  /**
   * In case the Short was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ShortUpdateInput, Prisma.ShortUncheckedUpdateInput>
}

/**
 * Short delete
 */
export type ShortDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Short
   */
  select?: Prisma.ShortSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Short
   */
  omit?: Prisma.ShortOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortInclude<ExtArgs> | null
  /**
   * Filter which Short to delete.
   */
  where: Prisma.ShortWhereUniqueInput
}

/**
 * Short deleteMany
 */
export type ShortDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Shorts to delete
   */
  where?: Prisma.ShortWhereInput
  /**
   * Limit how many Shorts to delete.
   */
  limit?: number
}

/**
 * Short.author
 */
export type Short$authorArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Short without action
 */
export type ShortDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Short
   */
  select?: Prisma.ShortSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Short
   */
  omit?: Prisma.ShortOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShortInclude<ExtArgs> | null
}
